version: "3"

services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3
    restart: always
    volumes:
      - nexus-data:/nexus-data
    ports:
      - "8082:8081"
      - "28079:18079"
volumes:
  nexus-data: {}
