version: '3.1'

services:

  redmine:
    image: redmine:4.2-alpine
    restart: always
    depends_on:
      - db
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: redmine
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
