version: "3"
services:
    sftp:
        image: atmoz/sftp
        ports:
            - "9922:22"
        command: foo:pass:1001:12345:/foo-home
        networks:
          - turreta_network     
networks:
  default:
    driver: bridge
