services:
  checkmk:
    image: checkmk/check-mk-raw:2.4.0-2024.11.12
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    ulimits:
      nofile: 1024
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - 'checkmk-data:/omd/sites'
    ports:
      - '8095:5000'
      - '6557:6557'
volumes:
  checkmk-data: {}
